### ISSUE TITLE
Allow for lazy resolution of subset of webview panels

### ISSUE THREAD

**Issue by sourishkrout** [stateful/tangle#37]
When multiple panels should up in a section (vscode UI) a tangle channel won't attach unless all of the panels have resolved (ie are visible). Let's figure out how to support this.

- [x] Come up with proposal
- [x] What to do about initial default state
- [x] Implement

**Comment by sourishkrout** [comment]
One approach, I've looked into before, is to make an instance of a tangle channel disposable, as in unsubscribing from all `onMessage` events and terminating pushing into `postMessage`. It was unclear just from reading the code much of this would already work. If disposability was given, one could generate a new tangle channel every time `register` fires with a different set of webview panels.

However, it's definitely be desirable for tangle to handle this internally.

**Comment by christian-bromann** [comment]
@sourishkrout I am not sure if this is related to tangle. Maybe the way it is used in your extension. I tried to reproduce this within `examples/worker_threads.js` and used this example:

```js
import { URL } from 'url';
import { Worker, isMainThread, workerData } from 'worker_threads';
import Channel from '../dist/esm/worker_threads.js';

const filename = new URL('', import.meta.url).pathname;

const ch = new Channel('test', {});

if (isMainThread) {
    const bus = await ch.registerPromise([
        new Worker(filename, { workerData: { id: 'worker #1' } }),
        new Worker(filename, { workerData: { id: 'worker #2' } }),
        new Worker(filename, { workerData: { id: 'worker #3' } })
    ]);

    bus.listen('onCustomEvent', (msg) =>
        console.log('Received from worker thread:', msg));

    bus.listen('onExit', (id) => {
        if (!id) {
            return;
        }
        console.log('Bye bye');
        ch.providers.map((p) => p.terminate());
    });

    setTimeout(() => bus.broadcast({ onCustomWorkerEvent: 'worker #3' }), 10000);
} else {
    console.log('INIT', workerData.id);
    setTimeout(() => {
        const client = ch.attach();

        /**
         * listen to events within the same sandbox
         */
        client.listen('onCustomEvent', (msg) =>
            console.log(`Another worker message received in ${workerData.id}; ${msg}`));

        /**
         * broadcast to all
         */
        console.log(';LOSS', workerData.id);
        client.broadcast({ onCustomEvent: `Hello from ${workerData.id} 👋` });

        /**
         * listen to messages from message bus
         */
        client.listen('onCustomWorkerEvent', (id) => {
            if (workerData.id === id) {
                client.broadcast({ 'onExit': workerData.id });
            }
        });
    }, workerData.id === 'worker #2' ? 5000 : 1000);
}
```

And the output is:
```js
Received from worker thread: undefined
INIT worker #1
INIT worker #2
INIT worker #3
Received from worker thread: Hello from worker #1 👋
;LOSS worker #1
Another worker message received in worker #1; Hello from worker #1 👋
;LOSS worker #3
Received from worker thread: Hello from worker #3 👋
Another worker message received in worker #1; Hello from worker #3 👋
Another worker message received in worker #3; Hello from worker #1 👋
Another worker message received in worker #3; Hello from worker #3 👋
;LOSS worker #2
Received from worker thread: Hello from worker #2 👋
Another worker message received in worker #2; Hello from worker #1 👋
Another worker message received in worker #3; Hello from worker #2 👋
Another worker message received in worker #1; Hello from worker #2 👋
Another worker message received in worker #2; Hello from worker #3 👋
Another worker message received in worker #2; Hello from worker #2 👋
Received from worker thread: Hello from worker #2 👋
Another worker message received in worker #2; Hello from worker #2 👋
Another worker message received in worker #3; Hello from worker #2 👋
Another worker message received in worker #1; Hello from worker #2 👋
Received from worker thread: Hello from worker #2 👋
Bye by
```

Which shows that communication happened even without having all worker threads attach to the channel. My assumption is that you are using `bus.whenReady()` which (as expected) only resolves when the amount of registered providers has connected to the channel.

**Comment by sourishkrout** [comment]
> ```js
> ```js
> 
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> Which shows that communication happened even without having all worker threads attach to the channel. My assumption is that you are using bus.whenReady() which (as expected) only resolves when the amount of registered providers has connected to the channel.
> ```

Actually, I don't think you will be able to reproduce the issue outside of Webviews without engineering around it, @christian-bromann. I believe all other supported DOM Implementations don't "resolve async". And by "async", I don't mean promise/observable, I mean that you can have an arbitrary number of Webviews that will be initialized & resolved based on their visibility status in the UX. Check out the GIF below that illustrates the problem. In fact, it looks like it's fine for successive Webview resolutions. However, it won't hook up tangle for partially resolutions.

![race](https://user-images.githubusercontent.com/250527/178610382-f520b472-345d-4053-a86a-81327846d211.gif)

**Comment by sourishkrout** [comment]
Completing this while the upstream PR stays open for now.
